# Generated by Django 4.1.7 on 2023-03-17 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetday', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
